# Generated by Django 5.1.1 on 2024-10-05 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion_del_curso', models.CharField(max_length=100)),
                ('descripcion_curso', models.TextField()),
                ('fecha_curso', models.DateField(default=datetime.date.today)),
                ('numero_horas', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
