# Generated by Django 5.1.1 on 2024-10-07 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0003_relacion_testimonios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referencias_laborales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_test', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
                ('relacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='porfolio.relacion')),
            ],
        ),
        migrations.DeleteModel(
            name='Testimonios',
        ),
    ]
